# Generated by Django 3.1.3 on 2020-12-04 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat_room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web_chat.chatroom', verbose_name='Chat_room'),
            preserve_default=False,
        ),
    ]
