# Generated by Django 3.1.3 on 2020-12-15 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_chat', '0002_auto_20201204_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
