# Generated by Django 3.1.3 on 2020-12-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_chat', '0003_auto_20201215_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
