# Generated by Django 3.1.3 on 2020-12-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_chat', '0004_auto_20201215_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='last_room_create',
            field=models.DateTimeField(null=True),
        ),
    ]
