# Generated by Django 3.1.3 on 2021-01-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_chat', '0006_chatroom_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(max_length=1500, verbose_name='Message_text'),
        ),
    ]
